### ISSUE TITLE
Enhancement, larger UI, more like the tablet interface on old webui

### ISSUE THREAD

**Issue by Ams-Laser** [Alex-CodeLab/webcnc#2]
the current bullseye jogging is just to small for cellphone control, something like the tablet mode gives more controll and less finger error for jog control
thanks
Ed

**Comment by Alex-CodeLab** [comment]
zoom in/out is now enabled for devices.  
For now that should work.

However, I'm not sure it that is the right way to go, because I think such an interface should always look exactly the same ( - scrolling could result in accidentally pushing a button).
